=== snetskf/LincolnPTPlace/WebService.asmx/dtd/colinx_get_hostping_001.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!--Generated by Turbo XML 2.3.0.100.-->

<!-- OAG Common Fields -->
<!-- End GETHOSTPING only fields and segments -->
<!ENTITY % STRDOM "(#PCDATA)">

<!ELEMENT AUTHID %STRDOM;>

<!ELEMENT CODEPAGE %STRDOM;>

<!ELEMENT COMPONENT %STRDOM;>

<!ELEMENT CONFIRMATION %STRDOM;>

<!ELEMENT DAY %STRDOM;>

<!ELEMENT HOUR %STRDOM;>

<!ELEMENT LANGUAGE %STRDOM;>

<!ELEMENT LOGICALID %STRDOM;>

<!ELEMENT MINUTE %STRDOM;>

<!ELEMENT MONTH %STRDOM;>

<!ELEMENT NOUN %STRDOM;>

<!ATTLIST NOUN  value CDATA  #IMPLIED >
<!ELEMENT REFERENCEID %STRDOM;>

<!ELEMENT REVISION %STRDOM;>

<!ATTLIST REVISION  value CDATA  #IMPLIED >
<!ELEMENT SECOND %STRDOM;>

<!ELEMENT SUBSECOND %STRDOM;>

<!ELEMENT TASK %STRDOM;>

<!ELEMENT TIMEZONE %STRDOM;>

<!ELEMENT VERB %STRDOM;>

<!ATTLIST VERB  value CDATA  #IMPLIED >
<!ELEMENT YEAR %STRDOM;>

<!-- End OAG Common Fields -->
<!-- OAG Complex Segments -->
<!ELEMENT BSR (VERB , NOUN , REVISION)>

<!ELEMENT CNTROLAREA (BSR , SENDER , DATETIME)>

<!ELEMENT SENDER (LOGICALID , COMPONENT , TASK , REFERENCEID , CONFIRMATION , LANGUAGE , CODEPAGE , AUTHID)>

<!ENTITY % SEG_DATETIME_QUALIFIERS_EXTENSION "OTHER | COLINX.CARDEXP | COLINX.REQUESTED">

<!ENTITY % SEG_DATETIME_QUALIFIERS "(ACCOUNTING | ACTEND | ACTSTART | APPREQ | APPROVAL | AVAILABLE |
            BKTEND | BKTSTART | CANCEL | CHANGEDATE | COMPDATE | CREATION | CUMULATIVE | DELIVACT | DELIVSCHED |
        DISCNT | DOCUMENT | DUE | EARLSTEFF | EARLSTSHIP | EFFECTIVE | ENGCHG | EXECFINISH |
            EXECSTART | EXPIRATION | FAILDATE | FORECASTF | FORECASTS | FROM | GENERATION |
            IMPL | INVOICE | LABORFINSH | LABORSTART | LASTUSED | LOADING |
            MATCHING | MSMENTDATE | NEEDDELV | OPFINISH | OPSTART | PAYEND |
            PLANEND | PLANSTART | PO | PROMDELV | PROMSHIP | PYMTTERM | RECEIVED | REPORTDATE |
            REPORTNGFN | REPORTNGST | REQUIRED | RESORCDWNF | RESORCDWNS |
            RSPDDATE | RSPDOCGEN | SCHEND | SCHSTART | SETUPFINSH | SETUPSTART | SHIP |
            SHIPSCHED | STATUSDATE | TEARDOWNF | TEARDOWNS | TO |
            %SEG_DATETIME_QUALIFIERS_EXTENSION;)">

<!ENTITY % SEG_DATETIME_TYPES_EXTENSION "OTHER ">

<!ENTITY % SEG_DATETIME_TYPES "(T | F | %SEG_DATETIME_TYPES_EXTENSION;)">

<!ELEMENT DATETIME (YEAR , MONTH , DAY , HOUR , MINUTE , SECOND , SUBSECOND , TIMEZONE)>

<!ATTLIST DATETIME  qualifier %SEG_DATETIME_QUALIFIERS; #REQUIRED

                      type %SEG_DATETIME_TYPES; #IMPLIED

                      index     CDATA  #IMPLIED >
<!---
     <table border="1">
     <tr><td><b>Description:</b></td><td>End OAG Common Segments </td></tr>
     <tr><td><b>Usage:</b></td><td>Required, if parent element is supplied</td></tr>
     <tr><td><b>Valid Values:</b></td><td>0,1, or 2</td></tr>
     </table>
-->
<!ELEMENT COLINX_HOSTID %STRDOM;>

<!ELEMENT GET_HOSTPING_001 (CNTROLAREA , DATAAREA+)>

<!ELEMENT DATAAREA (GETHOSTPING)>

<!ELEMENT GETHOSTPING (COLINX_HOSTID)>

=== snetskf/LincolnPTPlace/WebService.asmx/dtd/getHostPing.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?>
<!DOCTYPE GET_PRICELIST_001 SYSTEM "..\dtd\colinx_get_hostping_001.dtd">
<!--
    $Revision: 1.4 $
    CoLinx, LLC

	 Cowden	7.0.0   02/21/2001	Initial Release 

	 Notes:
		Example Document for a PTPlace HOSTPING

-->
<GET_HOSTPING_001>
	<CNTROLAREA>
		<BSR>
			<VERB>GET</VERB>
			<NOUN>HOSTPING</NOUN>
			<REVISION>001</REVISION>
		</BSR>
		<SENDER>
			<LOGICALID>SKFMRC</LOGICALID>      													<!-- The Store: six characters. While the FROM and TO
																												  Portions of the AUTHID can include CLXPTP, the LOGICALID
																												  always refers to the store the document relates to. Since a 
																												  since all user requests are related to a store, the LogicalID
																												  refers to that store	 -->
			<COMPONENT>PTPLACE</COMPONENT>   													<!-- Always PTPLACE -->
			<TASK>PING</TASK>																			<!-- Originating Event -->
			<REFERENCEID>BV10293848</REFERENCEID>												<!-- Colinx provides userid of requesting user -->
			<CONFIRMATION>1</CONFIRMATION>														<!-- only confirm on error allowed for this doc -->
			<LANGUAGE>ENG</LANGUAGE>																<!-- CoLinx allows only ENG here -->
			<CODEPAGE>UTF-8</CODEPAGE>																<!-- CoLinx allows only UTF-8 codepage -->
			<AUTHID>CLXPTP-SKFMRC-00000000000123456789-0001</AUTHID>						<!-- SENDER-RECIPIENT-dddddddddddddddddddd-xxxx   -->
		</SENDER>																						<!-- The third portion is a transaction number, which should remain
																											     Unchanged for all documents that are part of a single
																											     Conversation.  Backend systems should increment the sequence
																											     number when replying instead of creating a new transaction number -->	
		<DATETIME qualifier="CREATION">															<!-- Document creation date -->
			<YEAR>2001</YEAR>
			<MONTH>03</MONTH>
			<DAY>02</DAY>
			<HOUR>17</HOUR>
			<MINUTE>59</MINUTE>
			<SECOND>00</SECOND>
			<SUBSECOND>0000</SUBSECOND>
			<TIMEZONE>-0500</TIMEZONE>
		</DATETIME>
	</CNTROLAREA>
	<DATAAREA>
		<GETHOSTPING>
			<COLINX_HOSTID>ptbroker1.colinx.com</COLINX_HOSTID>									<!-- hostname of the originator -->
		</GETHOSTPING>
	</DATAAREA>
</GET_HOSTPING_001>
