=== snetskf/LincolnPTPlace/WebService.asmx/Classes/colinx_get_pricelist_002.dtd
<!-- OAG Common Fields -->
  <!ENTITY % STRDOM "(#PCDATA)">
  <!ELEMENT AUTHID %STRDOM;>
  <!ELEMENT CATALGNAME %STRDOM;>
  <!ELEMENT CODE %STRDOM;>
  <!ELEMENT CODEPAGE %STRDOM;>
  <!ELEMENT COMPONENT %STRDOM;>
  <!ELEMENT CONFIRMATION %STRDOM;>
  <!ELEMENT CURRENCY %STRDOM;>
  <!ELEMENT DAY %STRDOM;>
  <!ELEMENT DESCRIPTN %STRDOM;>
  <!ELEMENT DRCR %STRDOM;>
  <!ELEMENT HOUR %STRDOM;>
  <!ELEMENT LANGUAGE %STRDOM;>
  <!ELEMENT LINENUM %STRDOM;>
  <!ELEMENT LOGICALID %STRDOM;>
  <!ELEMENT MINUTE %STRDOM;>
  <!ELEMENT MONTH %STRDOM;>
  <!ELEMENT NOUN %STRDOM;>
  <!ATTLIST NOUN  value CDATA  #IMPLIED >
  <!ELEMENT NUMOFDEC %STRDOM;>
  <!ELEMENT OVERIDPRIC %STRDOM;>
  <!ELEMENT PARTNRID %STRDOM;>
  <!ELEMENT PRICELSTID %STRDOM;>
  <!ELEMENT PRICELSTRV %STRDOM;>
  <!ELEMENT PRICING_REFERENCE %STRDOM;>
  <!ELEMENT PRICING_UOM %STRDOM;>
  <!ELEMENT REFERENCEID %STRDOM;>
  <!ELEMENT REVISION %STRDOM;>
  <!ATTLIST REVISION  value CDATA  #IMPLIED >
  <!ELEMENT SECOND %STRDOM;>
  <!ELEMENT SIGN %STRDOM;>
  <!ELEMENT SITELEVEL %STRDOM;>
  <!ATTLIST SITELEVEL  index CDATA  #REQUIRED >
  <!ELEMENT SUBSECOND %STRDOM;>
  <!ELEMENT TASK %STRDOM;>
  <!ELEMENT TIMEZONE %STRDOM;>
  <!ELEMENT UOM %STRDOM;>
  <!ELEMENT UOMNUMDEC %STRDOM;>
  <!ELEMENT UOMVALUE %STRDOM;>
  <!ELEMENT USERAREA ANY>
  <!ELEMENT VALUE %STRDOM;>
  <!ELEMENT VERB %STRDOM;>
  <!ATTLIST VERB  value CDATA  #IMPLIED >
  <!ELEMENT YEAR %STRDOM;>
<!-- End OAG Common Fields -->
<!-- OAG Complex Segments -->
  <!ENTITY % SEG_AMOUNT_QUALIFIERS_EXTENSION "OTHER | COLINX.DISCMULT">
  <!ENTITY % SEG_AMOUNT_QUALIFIERS "(ACTUAL | APPRVORD | AVAILABLE | BUDGET | COMMISSION |
           DECLAREVAL | DSCPRCNT | DSCVALUE | DISCNT | DOCUMENT | ESTENGIMP | ESTFREIGHT | ESTHRS | ESTIMATE | ESTMANIMP |
            ESTUCOST | EXTENDED | FREIGHT | ITEM | OPENITEM | ORDER | ORDLIMIT |
            PAYRATE | RATE | PRCBRK | TAX | TAXBASE | TOTAL | TOTLIMIT |
            %SEG_AMOUNT_QUALIFIERS_EXTENSION;)">
  <!ENTITY % SEG_AMOUNT_TYPES_EXTENSION "OTHER ">
  <!ENTITY % SEG_AMOUNT_TYPES "(T | F | %SEG_AMOUNT_TYPES_EXTENSION;)">
  <!ELEMENT AMOUNT (VALUE , NUMOFDEC , SIGN , CURRENCY , DRCR)>
  <!ATTLIST AMOUNT  qualifier %SEG_AMOUNT_QUALIFIERS; #REQUIRED
                      type %SEG_AMOUNT_TYPES; #IMPLIED
                      index     CDATA  #IMPLIED ><!ENTITY % AMOUNT.ACTUAL "AMOUNT">
  <!ELEMENT BSR (VERB , NOUN , REVISION)>
  <!ELEMENT CNTROLAREA (BSR , SENDER , DATETIME)>
  <!ENTITY % SEG_DATETIME_QUALIFIERS_EXTENSION "OTHER | COLINX.CARDEXP | COLINX.REQUESTED">
  <!ENTITY % SEG_DATETIME_QUALIFIERS "(ACCOUNTING | ACTEND | ACTSTART | APPREQ | APPROVAL | AVAILABLE |
            BKTEND | BKTSTART | CANCEL | CHANGEDATE | COMPDATE | CREATION | CUMULATIVE | DELIVACT | DELIVSCHED |
        DISCNT | DOCUMENT | DUE | EARLSTEFF | EARLSTSHIP | EFFECTIVE | ENGCHG | EXECFINISH |
            EXECSTART | EXPIRATION | FAILDATE | FORECASTF | FORECASTS | FROM | GENERATION |
            IMPL | INVOICE | LABORFINSH | LABORSTART | LASTUSED | LOADING |
            MATCHING | MSMENTDATE | NEEDDELV | OPFINISH | OPSTART | PAYEND |
            PLANEND | PLANSTART | PO | PROMDELV | PROMSHIP | PYMTTERM | RECEIVED | REPORTDATE |
            REPORTNGFN | REPORTNGST | REQUIRED | RESORCDWNF | RESORCDWNS |
            RSPDDATE | RSPDOCGEN | SCHEND | SCHSTART | SETUPFINSH | SETUPSTART | SHIP |
            SHIPSCHED | STATUSDATE | TEARDOWNF | TEARDOWNS | TO |
            %SEG_DATETIME_QUALIFIERS_EXTENSION;)">
  <!ENTITY % SEG_DATETIME_TYPES_EXTENSION "OTHER ">
  <!ENTITY % SEG_DATETIME_TYPES "(T | F | %SEG_DATETIME_TYPES_EXTENSION;)">
  <!ELEMENT DATETIME (YEAR , MONTH , DAY , HOUR , MINUTE , SECOND , SUBSECOND , TIMEZONE)>
  <!ATTLIST DATETIME  qualifier %SEG_DATETIME_QUALIFIERS; #REQUIRED
                        type %SEG_DATETIME_TYPES; #IMPLIED
                        index     CDATA  #IMPLIED >
  <!ENTITY % SEG_OPERAMT_QUALIFIERS_EXTENSION "OTHER | LPRICE | RVPRICE">
  <!ENTITY % SEG_OPERAMT_QUALIFIERS "(COST | EXTENDED | FREIGHT | UNIT | %SEG_OPERAMT_QUALIFIERS_EXTENSION;)">
  <!ENTITY % SEG_OPERAMT_TYPES_EXTENSION "OTHER | LPRICE | RVPRICE">
  <!ENTITY % SEG_OPERAMT_TYPES "(T | F | %SEG_OPERAMT_TYPES_EXTENSION;)">
  <!ELEMENT OPERAMT (VALUE , NUMOFDEC , SIGN , CURRENCY , UOMVALUE , UOMNUMDEC , UOM)>
  <!ATTLIST OPERAMT  qualifier %SEG_OPERAMT_QUALIFIERS; #REQUIRED
                       type %SEG_OPERAMT_TYPES; #REQUIRED
   >
  <!ENTITY % SEG_QUANTITY_QUALIFIERS_EXTENSION "OTHER | COLINX.TOTWEIGHT | COLINX.ALLOWED | COLINX.ORDERED | COLINX.REMAIN">
  <!ENTITY % SEG_QUANTITY_QUALIFIERS "(ACCEPTED | ACTDUR | ACTHRS | ALLOCATED | ALLOWEDWT | AVAILABLE |
            AVGRUNSIZE | BACKORDERD | BATCHSIZE | BATCHTIME | BLOCKED | BREAKTIME |
            CAPPERCENT | CATCHWEGHT | COMMISSION | COMPLETED | CUMULATIVE | DELIVERED | DURATION | DUROVER | DURUNDER | EMPLOYEES |
            EMPREQD | ESTDUR | ESTHRS | ESTWEIGHT | FILENAME | FILESIZE | FIXEDTIME | HEIGHT | INSPECTED | INSPECTION | ITEM |
            LDTMOFFSET | LENGTH | LABOR | LOADINGWT | LOTSIZEMAX | LOTSIZEMIN | LOTSIZEMLT | LOWERLIMIT |
            MACHINEHRS | MAXIMUM | MAXPARLTM | MINIMUM | MOVETIME | MSMENT | MULTIPLIER | NETWEIGHT |
            OPEN | ORDERED | OTHERREJ | OVERSHIP | PACKING | PERCENT | PERCENTREQ |
            PERSHBNOPR | PERSHWIOPR | PLNDPRCT | PRCBRK | PRIOR | QUEUETIME | RATE | RECEIVED |
            REJECTED | REJPERCENT | REMDUR | REMHRS | REQUIRED | RETURNED | REWORK |
            RUNTIME | SCRAP | SETUPTIME | SHELFLIFE | SHIPPED | SHIPUNIT | TEARDOWN |
            TOOLREQD | TOTWEIGHT | TRANSFRLOT | UNDERSHIP | UNIT | UPPERLIMIT | VOLUME | WAITTIME | WEIGHT | WIDTH |
            %SEG_QUANTITY_QUALIFIERS_EXTENSION;)">
  <!ELEMENT QUANTITY (VALUE , NUMOFDEC , SIGN , UOM)>
  <!ATTLIST QUANTITY  qualifier %SEG_QUANTITY_QUALIFIERS; #REQUIRED>
  <!ELEMENT SENDER (LOGICALID , COMPONENT , TASK , REFERENCEID , CONFIRMATION , LANGUAGE , CODEPAGE , AUTHID)>
<!-- End OAG Common Segments -->
<!-- CoLinx Common Fields and Segments -->
  <!ELEMENT COLINX_OEMNUM %STRDOM;>
  <!ELEMENT COLINX_ORDERTYPE %STRDOM;>
  <!ELEMENT QTEID %STRDOM;>
  <!ELEMENT QTELINENUM %STRDOM;>
  <!ELEMENT QTESUBLINE %STRDOM;>
  <!ELEMENT QTETYPE %STRDOM;>
  
  <!ELEMENT PAYMETHOD %STRDOM;>
  <!ELEMENT PARTNRRATG %STRDOM;>
  <!ELEMENT TAXID %STRDOM;>
  <!ELEMENT TERMID %STRDOM;>
  <!ELEMENT TAXID %STRDOM;>
  <!ELEMENT ONETIME %STRDOM;>
  <!ELEMENT PARENTID %STRDOM;>
  <!ELEMENT PARTNRIDX %STRDOM;>
  <!ELEMENT NAME %STRDOM;>
  <!ATTLIST NAME index CDATA #REQUIRED>
  
  <!ELEMENT SYNCIND %STRDOM;>
  <!ELEMENT PARTNRTYPE %STRDOM;>
  <!ELEMENT TAXEXEMPT %STRDOM;>
  <!ELEMENT ACTIVE %STRDOM;>
  <!ELEMENT DUNSNUMBER %STRDOM;>
  <!ELEMENT PARTNRROLE %STRDOM;>
  
  <!ELEMENT COLINX_PREFNAME %STRDOM;>
  <!ELEMENT COLINX_PREFVALUE %STRDOM;>
  <!ELEMENT COLINX_PREFDESC %STRDOM;>
  
  <!ELEMENT COLINX_PREFERENCE (COLINX_PREFNAME,COLINX_PREFVALUE,COLINX_PREFDESC?)>
  <!ELEMENT COLINX_PARTNER_USERAREA (COLINX_PREFERENCE*)>
  
  <!ELEMENT ADDRLINE %STRDOM;>
  <!ATTLIST ADDRLINE index CDATA #REQUIRED>  
  
  <!ELEMENT ADDRTYPE %STRDOM;>
  <!ELEMENT CITY %STRDOM;>
  <!ELEMENT COUNTRY %STRDOM;>
  <!ELEMENT COUNTY %STRDOM;>  
  
  <!ELEMENT FAX %STRDOM;>  
  <!ATTLIST FAX index CDATA #REQUIRED>
  
  <!ELEMENT POSTALCODE %STRDOM;>
  <!ELEMENT REGION %STRDOM;>
  <!ELEMENT STATEPROVN %STRDOM;>
  <!ELEMENT TAXJRSDCTN %STRDOM;>
  <!ELEMENT TELEPHONE %STRDOM;>
  <!ATTLIST TELEPHONE index CDATA #REQUIRED>
  
  <!ELEMENT URL %STRDOM;>
  
  <!ELEMENT COLINX_LEGACYKEY %STRDOM;>
  
  <!ELEMENT COLINX_ADDRESS_USERAREA (COLINX_LEGACYKEY)>
  
  <!ELEMENT ADDRESS (ADDRLINE*,ADDRTYPE?,CITY?,COUNTRY?,COUNTY?,DESCRIPTN?,FAX*,POSTALCODE?,REGION?,STATEPROVN?,TAXJRSDCTN?,TELEPHONE*,URL?,COLINX_ADDRESS_USERAREA?)>
  <!ATTLIST ADDRESS returndata CDATA #IMPLIED>
  
  <!ELEMENT CONTCTTYPE %STRDOM;>
  <!ELEMENT EMAIL %STRDOM;>
  
  <!ELEMENT CONTACT (NAME,CONTCTTYPE?,DESCRIPTN?,EMAIL?,FAX*,NAME*,TELEPHONE*,USERAREA?)>
  <!ATTLIST CONTACT returndata CDATA #IMPLIED>

  <!ELEMENT PARTNER (NAME,ONETIME?,PARTNRID?,PARTNRTYPE?,SYNCIND?,ACTIVE?,CURRENCY?,DESCRIPTN?,DUNSNUMBER?,GLENTITYS?,PARENTID?,PARTNRIDX?,PARTNRRATG?,PARTNRROLE?,PAYMETHOD?,TAXEXEMPT?,TAXID?,TERMID?,COLINX_PARTNER_USERAREA?,ADDRESS*,CONTACT*)>
  <!ATTLIST PARTNER returndata CDATA #IMPLIED>

  <!ELEMENT PARTTYPE %STRDOM;>
  <!ELEMENT PARTNO %STRDOM;>
  <!ELEMENT PARTCLASS %STRDOM;>
  <!ELEMENT PARTKEY %STRDOM;>
  <!ELEMENT PARTQUAL %STRDOM;>
  <!ELEMENT PARTDESC %STRDOM;>
  <!ELEMENT PRIORITY %STRDOM;>
  <!ELEMENT PARTREF ( PARTTYPE, PARTNO, PARTCLASS?, PARTKEY?, PARTQUAL?, PARTDESC?, PRIORITY?)>
  <!ELEMENT COLINX_QTEREF ( QTEID, QTETYPE?, QTELINENUM?, QTESUBLINE? )>
  
  <!ELEMENT COLINX_FRTBILLTYPE %STRDOM;>
  <!ELEMENT COLINX_DEVIATEFLG %STRDOM;>
  <!ELEMENT COLINX_PARTSHIP %STRDOM;>
  <!ELEMENT COLINX_FRTACCTNUM %STRDOM;>
  <!ELEMENT COLINX_WIC %STRDOM;>
  <!ELEMENT COLINX_CONSOLFLG %STRDOM;>
  <!ELEMENT COLINX_SHIPCMNT %STRDOM;>
  <!ELEMENT DESTCNTRY %STRDOM;>
  
  <!ELEMENT CC_TYPE %STRDOM;>
  <!ELEMENT CC_NUMBER %STRDOM;>
  <!ELEMENT CC_VALID_T %STRDOM;>
  <!ELEMENT CC_NAME %STRDOM;>
  <!ELEMENT COLINX_CCAUTH (CC_TYPE?, CC_NUMBER?, CC_VALID_T?, CC_NAME? )>
  
  <!ELEMENT COLINX_SHIPINSTR (COLINX_ORDERTYPE?,COLINX_FRTBILLTYPE?,COLINX_CCAUTH?,COLINX_DEVIATEFLG?,COLINX_PARTSHIP?,COLINX_FRTACCTNUM?,COLINX_WIC?,COLINX_CONSOLFLG?,COLINX_SHIPCMNT?,DESTCNTRY?)>
  
  <!ELEMENT SPECIAL_INSTRUCTION (CODE?, DESCRIPTN?)>
  <!ELEMENT SPECIAL_INSTRUCTIONS (SPECIAL_INSTRUCTION*)>

  <!ELEMENT PACKING %STRDOM;> <!-- Added for OEM -->
  <!ELEMENT REQUEST_SHIPMENT_OPTIONS %STRDOM;>
  <!ELEMENT REQUEST_FREIGHT_CHARGE %STRDOM;>
<!-- End Colinx Common Fields and Segments -->
<!-- GET_PRICELIST only fields and segments -->
  <!ELEMENT GET_PRICELIST_002 (CNTROLAREA , DATAAREA+)>
  <!ELEMENT DATAAREA (GET_PRICELIST)>
  <!ELEMENT GET_PRICELIST (PRICELIST)>
  <!ELEMENT PRICELIST_USERAREA (QTEID?, COLINX_OEMNUM?, REQUEST_FREIGHT_CHARGE?, (COLINX_SHIPINSTR)?)>
  <!ELEMENT PRCLSTLINE_USERAREA ( (DATETIME)?, (QUANTITY)? , SITELEVEL? ,PACKING?, REQUEST_SHIPMENT_OPTIONS?, COLINX_QTEREF?,PRICING_REFERENCE?,PRICING_UOM?, SPECIAL_INSTRUCTIONS?)>
  <!ELEMENT PRICELIST ((DATETIME)? , PRICELSTID , PARTNRID , CURRENCY? , DESCRIPTN? , PRICELSTRV? , PRICELIST_USERAREA? , PARTNER*, PRCLSTLINE* , LISTPRCBRK* , PRCLSTQUAL*)>
  <!ATTLIST PRICELIST  returndata CDATA  #REQUIRED >
  <!ELEMENT PRCLSTLINE ( (OPERAMT)? , DESCRIPTN? , LINENUM? , PARTREF+, PRCLSTLINE_USERAREA? , LINEPRCBRK*)>
  <!ATTLIST PRCLSTLINE  returndata CDATA  #REQUIRED >
  <!ELEMENT LINEPRCBRK (DESCRIPTN? , USERAREA? , (QUANTITY)? , (AMOUNT)? , OVERIDPRIC?)>
  <!ATTLIST LINEPRCBRK  returndata CDATA  #REQUIRED >
  <!ELEMENT LISTPRCBRK ((AMOUNT)* , DESCRIPTN? , USERAREA?)>
  <!ATTLIST LISTPRCBRK  returndata CDATA  #REQUIRED >
  <!ELEMENT PRCLSTQUAL (DESCRIPTN? , SITELEVEL* , USERAREA? , CATALGNAME? , PARTNRID?)>
  <!ATTLIST PRCLSTQUAL  returndata CDATA  #REQUIRED >
<!-- GET_PRICELIST only fields and segments -->

=== snetskf/LincolnPTPlace/WebService.asmx/xmls/get_pricelist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GET_PRICELIST_002 SYSTEM "colinx_get_pricelist_002.dtd">
<GET_PRICELIST_002>
	<CNTROLAREA>
		<BSR>
			<VERB>GET</VERB>
			<NOUN>PRICELIST</NOUN>
			<REVISION>002</REVISION>
		</BSR>
		<SENDER>
			<LOGICALID>SKFSKF</LOGICALID>
			<COMPONENT>PTPLACE</COMPONENT>
			<TASK>GET</TASK>
			<REFERENCEID>code=PTPlace,customer=60599,origin=ptpr,storeid=SKFSKF,userid=85077</REFERENCEID>
			<CONFIRMATION>0</CONFIRMATION>
			<LANGUAGE>ENG</LANGUAGE>
			<CODEPAGE>UTF-8</CODEPAGE>
			<AUTHID>CLXPTP-SKFSKF-00015887693980054222-0001</AUTHID>
		</SENDER>
		<DATETIME qualifier="CREATION">
			<YEAR>2020</YEAR>
			<MONTH>5</MONTH>
			<DAY>6</DAY>
			<HOUR>8</HOUR>
			<MINUTE>49</MINUTE>
			<SECOND>58</SECOND>
			<SUBSECOND>7</SUBSECOND>
			<TIMEZONE>-0400</TIMEZONE>
		</DATETIME>
	</CNTROLAREA>
	<DATAAREA>
		<GET_PRICELIST>
			<PRICELIST returndata="1">
				<PRICELSTID>Customer</PRICELSTID>
				<PARTNRID>60599</PARTNRID>
				<CURRENCY>USD</CURRENCY>
				<PRICELIST_USERAREA/>
				<PRCLSTLINE returndata="1">
					<LINENUM>1</LINENUM>
					<PARTREF>
						<PARTTYPE>Manufacturer</PARTTYPE>
						<PARTNO>6203</PARTNO>
						<PARTCLASS></PARTCLASS>
						<PARTKEY>0000427</PARTKEY>
						<PARTQUAL>Manufacturer</PARTQUAL>
					</PARTREF>
					<PRCLSTLINE_USERAREA>
						<DATETIME qualifier="REQUIRED">
							<YEAR>2020</YEAR>
							<MONTH>5</MONTH>
							<DAY>6</DAY>
							<HOUR>0</HOUR>
							<MINUTE>0</MINUTE>
							<SECOND>0</SECOND>
							<SUBSECOND>0</SUBSECOND>
							<TIMEZONE>-0400</TIMEZONE>
						</DATETIME>
						<QUANTITY qualifier="OTHER">
							<VALUE>1</VALUE>
							<NUMOFDEC>0</NUMOFDEC>
							<SIGN>+</SIGN>
							<UOM>EA</UOM>
						</QUANTITY>
						<SITELEVEL index="1">DEFAULT</SITELEVEL>
						<PACKING>DEFAULT</PACKING>
					</PRCLSTLINE_USERAREA>
				</PRCLSTLINE>
			</PRICELIST>
		</GET_PRICELIST>
	</DATAAREA>
</GET_PRICELIST_002>
