=== snetskf/LincolnPTPlace/WebService.asmx/Classes/colinx_show_pricelist_002.dtd
<!-- OAG Common Fields -->
  <!ENTITY % STRDOM "(#PCDATA)">
  <!ELEMENT AUTHID %STRDOM;>
  <!ELEMENT BUSNAREA %STRDOM;>
  <!ELEMENT CATALGNAME %STRDOM;>
  <!ELEMENT CHARGEID %STRDOM;>
  <!ELEMENT CHARGETYPE %STRDOM;>
  <!ELEMENT CHGLINENUM %STRDOM;>
  <!ELEMENT CODE %STRDOM;>
  <!ELEMENT CODEPAGE %STRDOM;>
  <!ELEMENT COMPONENT %STRDOM;>
  <!ELEMENT CONFIRMATION %STRDOM;>
  <!ELEMENT COSTCENTER %STRDOM;>
  <!ELEMENT CURRENCY %STRDOM;>
  <!ELEMENT DAY %STRDOM;>
  <!ELEMENT DEPARTMENT %STRDOM;>
  <!ELEMENT DESCRIPTN %STRDOM;>
  <!ELEMENT DIVISION %STRDOM;>
  <!ELEMENT DRCR %STRDOM;>
  <!ELEMENT ELEMENT %STRDOM;>
  <!ATTLIST ELEMENT
          index CDATA #REQUIRED
  >
  <!ELEMENT FUND %STRDOM;>
  <!ELEMENT GEOGRAPHY %STRDOM;>
  <!ELEMENT GLENTITYS %STRDOM;>
  <!ELEMENT GLNOMACCT %STRDOM;>
  <!ELEMENT HOUR %STRDOM;>
  <!ELEMENT ITEMTYPE %STRDOM;>
  <!ELEMENT LANGUAGE %STRDOM;>
  <!ELEMENT LINENUM %STRDOM;>
  <!ELEMENT LOGICALID %STRDOM;>
  <!ELEMENT MINUTE %STRDOM;>
  <!ELEMENT MONTH %STRDOM;>
  <!ELEMENT NOUN %STRDOM;>
  <!ATTLIST NOUN  value CDATA  #IMPLIED >
  <!ELEMENT NUMOFDEC %STRDOM;>
  <!ELEMENT OVERIDPRIC %STRDOM;>
  <!ELEMENT PARTNRID %STRDOM;>
  <!ELEMENT PRICELSTID %STRDOM;>
  <!ELEMENT PRICELSTRV %STRDOM;>
  <!ELEMENT PRICING_REFERENCE %STRDOM;>  
  <!ELEMENT PRDLINENUM %STRDOM;>
  <!ELEMENT PRODORDID %STRDOM;>
  <!ELEMENT PROFITCTR %STRDOM;>
  <!ELEMENT PROJECT %STRDOM;>
  <!ELEMENT REASONCODE %STRDOM;>
  <!ELEMENT REFERENCEID %STRDOM;>
  <!ELEMENT REVISION %STRDOM;>
  <!ATTLIST REVISION  value CDATA  #IMPLIED >
  <!ELEMENT SECOND %STRDOM;>
  <!ELEMENT SIGN %STRDOM;>
  <!ELEMENT SITELEVEL %STRDOM;>
  <!ATTLIST SITELEVEL  index CDATA  #REQUIRED >
  <!ELEMENT SUBSECOND %STRDOM;>
  <!ELEMENT TASK %STRDOM;>
  <!ELEMENT TIMEZONE %STRDOM;>
  <!ELEMENT UOM %STRDOM;>
  <!ELEMENT UOMNUMDEC %STRDOM;>
  <!ELEMENT UOMVALUE %STRDOM;>
  <!ELEMENT UNIT %STRDOM;>
  <!ELEMENT USERAREA ANY>
  <!ELEMENT VALUE %STRDOM;>
  <!ELEMENT VERB %STRDOM;>
  <!ATTLIST VERB  value CDATA  #IMPLIED ><!ELEMENT YEAR %STRDOM;>
  <!ELEMENT WAREHOUSE %STRDOM;>
<!-- End OAG Common Fields -->
<!-- OAG Complex Segments -->
  <!ENTITY % SEG_AMOUNT_QUALIFIERS_EXTENSION "OTHER | COLINX.DISCMULT">
  <!ENTITY % SEG_AMOUNT_QUALIFIERS "(ACTUAL | APPRVORD | AVAILABLE | BUDGET | COMMISSION |
           DECLAREVAL | DSCPRCNT | DSCVALUE | DISCNT | DOCUMENT | ESTENGIMP | ESTFREIGHT | ESTHRS | ESTIMATE | ESTMANIMP |
            ESTUCOST | EXTENDED | FREIGHT | ITEM | OPENITEM | ORDER | ORDLIMIT |
            PAYRATE | RATE | PRCBRK | TAX | TAXBASE | TOTAL | TOTLIMIT |
            %SEG_AMOUNT_QUALIFIERS_EXTENSION;)">
  <!ENTITY % SEG_AMOUNT_TYPES_EXTENSION "OTHER ">
  <!ENTITY % SEG_AMOUNT_TYPES "(T | F | %SEG_AMOUNT_TYPES_EXTENSION;)">
  <!ELEMENT AMOUNT (VALUE , NUMOFDEC , SIGN , CURRENCY , DRCR)>
  <!ATTLIST AMOUNT  qualifier %SEG_AMOUNT_QUALIFIERS; #REQUIRED
                      type %SEG_AMOUNT_TYPES; #IMPLIED
                      index     CDATA  #IMPLIED ><!ENTITY % AMOUNT.ACTUAL "AMOUNT">
  <!ELEMENT BSR (VERB , NOUN , REVISION)>
  <!ELEMENT CNTROLAREA (BSR , SENDER , DATETIME)>
  <!ENTITY % SEG_DATETIME_QUALIFIERS_EXTENSION "OTHER | COLINX.CARDEXP | COLINX.REQUESTED">
  <!ENTITY % SEG_DATETIME_QUALIFIERS "(ACCOUNTING | ACTEND | ACTSTART | APPREQ | APPROVAL | AVAILABLE |
            BKTEND | BKTSTART | CANCEL | CHANGEDATE | COMPDATE | CREATION | CUMULATIVE | DELIVACT | DELIVSCHED |
        DISCNT | DOCUMENT | DUE | EARLSTEFF | EARLSTSHIP | EFFECTIVE | ENGCHG | EXECFINISH |
            EXECSTART | EXPIRATION | FAILDATE | FORECASTF | FORECASTS | FROM | GENERATION |
            IMPL | INVOICE | LABORFINSH | LABORSTART | LASTUSED | LOADING |
            MATCHING | MSMENTDATE | NEEDDELV | OPFINISH | OPSTART | PAYEND |
            PLANEND | PLANSTART | PO | PROMDELV | PROMSHIP | PYMTTERM | RECEIVED | REPORTDATE |
            REPORTNGFN | REPORTNGST | REQUIRED | RESORCDWNF | RESORCDWNS |
            RSPDDATE | RSPDOCGEN | SCHEND | SCHSTART | SETUPFINSH | SETUPSTART | SHIP |
            SHIPSCHED | STATUSDATE | TEARDOWNF | TEARDOWNS | TO |
            %SEG_DATETIME_QUALIFIERS_EXTENSION;)">
  <!ENTITY % SEG_DATETIME_TYPES_EXTENSION "OTHER ">
  <!ENTITY % SEG_DATETIME_TYPES "(T | F | %SEG_DATETIME_TYPES_EXTENSION;)">
  <!ELEMENT DATETIME (YEAR , MONTH , DAY , HOUR , MINUTE , SECOND , SUBSECOND , TIMEZONE)>
  <!ATTLIST DATETIME  qualifier %SEG_DATETIME_QUALIFIERS; #REQUIRED
                        type %SEG_DATETIME_TYPES; #IMPLIED
                        index     CDATA  #IMPLIED >
  <!ENTITY % SEG_OPERAMT_QUALIFIERS_EXTENSION "OTHER | LPRICE | RVPRICE | SHIPPING">
  <!ENTITY % SEG_OPERAMT_QUALIFIERS "(COST | EXTENDED | EXTENDED_INCL_TAX | FREIGHT | UNIT | %SEG_OPERAMT_QUALIFIERS_EXTENSION;)">
  <!ENTITY % SEG_OPERAMT_TYPES_EXTENSION "OTHER | LPRICE | RVPRICE | S">
  <!ENTITY % SEG_OPERAMT_TYPES "(T | F | %SEG_OPERAMT_TYPES_EXTENSION;)">
  <!ELEMENT OPERAMT (VALUE , NUMOFDEC , SIGN , CURRENCY , DRCR?, UOMVALUE , UOMNUMDEC , UOM)>
  <!ATTLIST OPERAMT  qualifier %SEG_OPERAMT_QUALIFIERS; #REQUIRED
                       type %SEG_OPERAMT_TYPES; #REQUIRED
   >
  <!ENTITY % SEG_QUANTITY_QUALIFIERS_EXTENSION "OTHER | COLINX.TOTWEIGHT | COLINX.ALLOWED | COLINX.ORDERED | COLINX.REMAIN">
  <!ENTITY % SEG_QUANTITY_QUALIFIERS "(ACCEPTED | ACTDUR | ACTHRS | ALLOCATED | ALLOWEDWT | AVAILABLE |
            AVGRUNSIZE | BACKORDERD | BATCHSIZE | BATCHTIME | BLOCKED | BREAKTIME |
            CAPPERCENT | CATCHWEGHT | COMMISSION | COMPLETED | CUMULATIVE | DELIVERED | DURATION | DUROVER | DURUNDER | EMPLOYEES |
            EMPREQD | ESTDUR | ESTHRS | ESTWEIGHT | FILENAME | FILESIZE | FIXEDTIME | HEIGHT | INSPECTED | INSPECTION | ITEM |
            LDTMOFFSET | LENGTH | LABOR | LOADINGWT | LOTSIZEMAX | LOTSIZEMIN | LOTSIZEMLT | LOWERLIMIT |
            MACHINEHRS | MAXIMUM | MAXPARLTM | MINIMUM | MOVETIME | MSMENT | MULTIPLIER | NETWEIGHT |
            OPEN | ORDERED | OTHERREJ | OVERSHIP | PACKING | PERCENT | PERCENTREQ |
            PERSHBNOPR | PERSHWIOPR | PLNDPRCT | PRCBRK | PRIOR | QUEUETIME | RATE | RECEIVED |
            REJECTED | REJPERCENT | REMDUR | REMHRS | REQUIRED | RETURNED | REWORK |
            RUNTIME | SCRAP | SETUPTIME | SHELFLIFE | SHIPPED | SHIPUNIT | TEARDOWN |
            TOOLREQD | TOTWEIGHT | TRANSFRLOT | UNDERSHIP | UNIT | UPPERLIMIT | VOLUME | WAITTIME | WEIGHT | WIDTH |
            %SEG_QUANTITY_QUALIFIERS_EXTENSION;)">
  <!ELEMENT QUANTITY (VALUE , NUMOFDEC , SIGN , UOM)>
  <!ATTLIST QUANTITY  qualifier %SEG_QUANTITY_QUALIFIERS; #REQUIRED
   >
  <!ELEMENT SENDER (LOGICALID , COMPONENT , TASK , REFERENCEID , CONFIRMATION , LANGUAGE , CODEPAGE , AUTHID)>
  <!ELEMENT DISTRIBUTN ((OPERAMT)?, BUSNAREA?, COSTCENTER?, DEPARTMENT?, DIVISION?, ELEMENT*, FUND?, GEOGRAPHY?, GLENTITYS?, GLNOMACCT?, PROFITCTR?, PROJECT?, UNIT?, WAREHOUSE?, USERAREA?)>
  <!ATTLIST DISTRIBUTN
          returndata CDATA #IMPLIED
  >
  <!ELEMENT CHARGE ((OPERAMT)?, CHARGEID?, CHARGETYPE?, CHGLINENUM?, DESCRIPTN?, USERAREA?, DISTRIBUTN*)>
  <!ATTLIST CHARGE
          returndata CDATA #IMPLIED
  >
<!-- End OAG Common Segments -->
<!-- CoLinx Common Fields and Segments -->
  <!ELEMENT COLINX_AVAILDESC %STRDOM;>
  <!ELEMENT COLINX_BREAKSEQ %STRDOM;>
  <!ELEMENT COLINX_DISCCLASS %STRDOM;>
  <!ELEMENT COLINX_DISCMULT %STRDOM;>
  <!ELEMENT COLINX_INSTOCK %STRDOM;>
  <!ELEMENT COLINX_HOWPRICED %STRDOM;>
  <!ELEMENT COLINX_OEMNUM %STRDOM;>
  <!ELEMENT COLINX_ORDERTYPE %STRDOM;>
  <!ELEMENT COLINX_PRICETYPE %STRDOM;>
  <!ELEMENT COLINX_PRICEREF %STRDOM;>
  <!ELEMENT COLINX_SORTORDER %STRDOM;>

  <!ELEMENT ORDERABLE %STRDOM;>
  <!ELEMENT DEFAULTIND %STRDOM;>

  <!ELEMENT QTEID %STRDOM;>
  <!ELEMENT QTELINENUM %STRDOM;>
  <!ELEMENT QTESUBLINE %STRDOM;>
  <!ELEMENT QTETYPE %STRDOM;>
  <!ELEMENT COLINX_QTEREF ( QTEID, QTETYPE?, QTELINENUM?, QTESUBLINE? )>
  <!ELEMENT COLINX_STATUS (REASONCODE , DESCRIPTN?)>
  
  <!ELEMENT COLINX_FRTBILLTYPE %STRDOM;>
  <!ELEMENT COLINX_DEVIATEFLG %STRDOM;>
  <!ELEMENT COLINX_PARTSHIP %STRDOM;>
  <!ELEMENT COLINX_FRTACCTNUM %STRDOM;>
  <!ELEMENT COLINX_WIC %STRDOM;>
  <!ELEMENT COLINX_CONSOLFLG %STRDOM;>
  <!ELEMENT COLINX_SHIPCMNT %STRDOM;>
  <!ELEMENT DESTCNTRY %STRDOM;>
  
  <!ELEMENT CC_TYPE %STRDOM;>
  <!ELEMENT CC_NUMBER %STRDOM;>
  <!ELEMENT CC_VALID_T %STRDOM;>
  <!ELEMENT CC_NAME %STRDOM;>
  <!ELEMENT COLINX_CCAUTH (CC_TYPE?, CC_NUMBER?, CC_VALID_T?, CC_NAME? )> 
  
  <!ELEMENT COLINX_SHIPINSTR (COLINX_ORDERTYPE?,COLINX_FRTBILLTYPE?,COLINX_CCAUTH?,COLINX_DEVIATEFLG?,COLINX_PARTSHIP?,COLINX_FRTACCTNUM?,COLINX_WIC?,COLINX_CONSOLFLG?,COLINX_SHIPCMNT?,DESTCNTRY?)>
  
  <!ELEMENT LEAD_TIME  %STRDOM;>
  <!ATTLIST LEAD_TIME  UOM CDATA  #REQUIRED >
  
  <!ELEMENT MATERIAL  %STRDOM;>
  <!ELEMENT PLANT  %STRDOM;>
  <!ELEMENT TYPE   %STRDOM;>

  <!ELEMENT PACKING %STRDOM;> <!-- Added for OEM -->
  <!ELEMENT WHSEDETAIL ( (QUANTITY) , (COLINX_AVAILDESC | DATETIME) , SITELEVEL? , ORDERABLE?, PRODORDID?, PRIORITY? , PRDLINENUM?, COLINX_SORTORDER?, DEFAULTIND?)>

  <!ELEMENT PARTTYPE %STRDOM;>
  <!ELEMENT PARTNO %STRDOM;>
  <!ELEMENT PARTCLASS %STRDOM;>
  <!ELEMENT PARTKEY %STRDOM;>
  <!ELEMENT PARTQUAL %STRDOM;>
  <!ELEMENT PARTDESC %STRDOM;>
  <!ELEMENT PRIORITY %STRDOM;>
  <!ELEMENT PARTREF ( PARTTYPE, PARTNO, PARTCLASS?, PARTKEY?, PARTQUAL?, PARTDESC?, PRIORITY?)>
  <!ELEMENT COLINX_PRODAVAIL (DEFAULTIND?, COLINX_SORTORDER?, PACKING?, OPERAMT?,QUANTITY*,WHSEDETAIL+)>
  
  <!ELEMENT MANUFACTURE (LEAD_TIME?, MATERIAL?, PLANT?, TYPE?)>
  
  <!ELEMENT SPECIAL_INSTRUCTION (CODE?, DESCRIPTN?)>
  <!ELEMENT SPECIAL_INSTRUCTIONS (SPECIAL_INSTRUCTION*)>
  
  <!ELEMENT SORT_ORDER %STRDOM;>
  <!ELEMENT LIMIT_ORDERABLE_QUANTITY %STRDOM;>
  <!ELEMENT SHIPMENT_GROUP %STRDOM;>
  <!ELEMENT SHIPMENT_OPTION (SORT_ORDER?, LIMIT_ORDERABLE_QUANTITY?, SITELEVEL?, SHIPMENT_GROUP, (CHARGE)?)>
  
  <!ELEMENT REQUEST_FREIGHT_CHARGE %STRDOM;>
<!-- End Colinx Common Fields and Segments -->
<!-- SHOW_PRICELIST only fields and segments -->
  <!ELEMENT PRICELIST_USERAREA (QTEID? , COLINX_OEMNUM?, REQUEST_FREIGHT_CHARGE?, (COLINX_SHIPINSTR)?, (OPERAMT)*, (QUANTITY)?, (CHARGE)*)>
  
  <!ELEMENT COLINX_CONTRACTDESC %STRDOM;>
  <!ELEMENT PRCLSTLINE_USERAREA (COLINX_INSTOCK, (DATETIME) , (QUANTITY)*, COLINX_STATUS , COLINX_DISCCLASS? , SITELEVEL?, MANUFACTURE?,SHIPMENT_OPTION*,COLINX_PRODAVAIL*,COLINX_QTEREF?,ITEMTYPE?,CHARGE*, (OPERAMT)?,COLINX_CONTRACTDESC?,PRICING_REFERENCE?,SPECIAL_INSTRUCTIONS?)>
  <!ELEMENT LINEPRCBRK_USERAREA (COLINX_PRICETYPE , COLINX_BREAKSEQ, COLINX_DISCMULT?,COLINX_HOWPRICED?,COLINX_PRICEREF?)>
  <!ELEMENT SHOW_PRICELIST_002 (CNTROLAREA , DATAAREA+)>
  <!ELEMENT DATAAREA (SHOW_PRICELIST)>
  <!ELEMENT SHOW_PRICELIST (PRICELIST)>
  <!ELEMENT PRICELIST (DATETIME* , PRICELSTID , CURRENCY? , DESCRIPTN? , PRICELSTRV? , PARTNRID? , PRICELIST_USERAREA? , PRCLSTLINE* , LISTPRCBRK* , PRCLSTQUAL*)>
  <!ELEMENT PRCLSTLINE ((OPERAMT)+ , DESCRIPTN? , LINENUM? , PARTREF+, PRCLSTLINE_USERAREA? , LINEPRCBRK*)>
  <!ELEMENT LINEPRCBRK (DESCRIPTN? , LINEPRCBRK_USERAREA? , ((AMOUNT) | (QUANTITY))? , OVERIDPRIC?)>
  <!ELEMENT LISTPRCBRK ((AMOUNT)? , DESCRIPTN? , USERAREA?)>
  <!ELEMENT PRCLSTQUAL (DESCRIPTN? , SITELEVEL* , USERAREA? , CATALGNAME? , PARTNRID?)>
<!-- End SHOW_PRICELIST only fields and segments -->

=== snetskf/LincolnPTPlace/WebService.asmx/xmls/show_pricelist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SHOW_PRICELIST_002 SYSTEM 'colinx_show_pricelist_002.dtd'><SHOW_PRICELIST_002>
    <CNTROLAREA>
        <BSR>
            <VERB>SHOW</VERB>
            <NOUN>PRICELIST</NOUN>
            <REVISION>002</REVISION>
        </BSR>
        <SENDER>
            <LOGICALID>SKFSKF</LOGICALID>
            <COMPONENT>PTPLACE</COMPONENT>
            <TASK>SHOW</TASK>
            <REFERENCEID>CLXPTP-SKFSKF-00015887693980054222-0001</REFERENCEID>
            <CONFIRMATION>0</CONFIRMATION>
            <LANGUAGE>ENG</LANGUAGE>
            <CODEPAGE>UTF-8</CODEPAGE>
            <AUTHID>SKFSKF-CLXPTP-00015887693980054222-0002</AUTHID>
        </SENDER>
        <DATETIME qualifier="CREATION">
            <YEAR>2020</YEAR>
            <MONTH>5</MONTH>
            <DAY>6</DAY>
            <HOUR>14</HOUR>
            <MINUTE>49</MINUTE>
            <SECOND>59</SECOND>
            <SUBSECOND>707</SUBSECOND>
            <TIMEZONE>+0100</TIMEZONE>
        </DATETIME>
    </CNTROLAREA>
    <DATAAREA>
        <SHOW_PRICELIST>
            <PRICELIST>
                <PRICELSTID>Customer</PRICELSTID>
                <CURRENCY>USD</CURRENCY>
                <PARTNRID>60599</PARTNRID>
                <PRCLSTLINE>
                    <OPERAMT qualifier="UNIT" type="T">
                        <VALUE>537</VALUE>
                        <NUMOFDEC>2</NUMOFDEC>
                        <SIGN>+</SIGN>
                        <CURRENCY>USD</CURRENCY>
                        <UOMVALUE>10000</UOMVALUE>
                        <UOMNUMDEC>4</UOMNUMDEC>
                        <UOM>EA</UOM>
                    </OPERAMT>
                    <LINENUM>1</LINENUM>
                    <PARTREF>
                        <PARTTYPE>Manufacturer</PARTTYPE>
                        <PARTNO>6203</PARTNO>
                        <PARTKEY>0000427</PARTKEY>
                        <PARTQUAL>Manufacturer</PARTQUAL>
                    </PARTREF>
                    <PRCLSTLINE_USERAREA>
                        <COLINX_INSTOCK>INSTOCK</COLINX_INSTOCK>
                        <DATETIME qualifier="REQUIRED">
                            <YEAR>2020</YEAR>
                            <MONTH>05</MONTH>
                            <DAY>06</DAY>
                            <HOUR>00</HOUR>
                            <MINUTE>00</MINUTE>
                            <SECOND>00</SECOND>
                            <SUBSECOND>0000</SUBSECOND>
                            <TIMEZONE>-0500</TIMEZONE>
                        </DATETIME>
                        <QUANTITY qualifier="ORDERED">
                            <VALUE>1</VALUE>
                            <NUMOFDEC>0</NUMOFDEC>
                            <SIGN>+</SIGN>
                            <UOM>EA</UOM>
                        </QUANTITY>
                        <COLINX_STATUS>
                            <REASONCODE>0000</REASONCODE>
                        </COLINX_STATUS>
                        <SITELEVEL index="1">MyWrhse</SITELEVEL>
                        <COLINX_PRODAVAIL>
                            <DEFAULTIND>Y</DEFAULTIND>
                            <COLINX_SORTORDER>1</COLINX_SORTORDER>
                            <PACKING>12</PACKING>
                            <QUANTITY qualifier="LOTSIZEMIN">
                                <VALUE>1</VALUE>
                                <NUMOFDEC>0</NUMOFDEC>
                                <SIGN>+</SIGN>
                                <UOM>EA</UOM>
                            </QUANTITY>
                            <QUANTITY qualifier="LOTSIZEMLT">
                                <VALUE>1</VALUE>
                                <NUMOFDEC>0</NUMOFDEC>
                                <SIGN>+</SIGN>
                                <UOM>EA</UOM>
                            </QUANTITY>
                            <WHSEDETAIL>
                                <QUANTITY qualifier="AVAILABLE">
                                    <VALUE>0</VALUE>
                                    <NUMOFDEC>0</NUMOFDEC>
                                    <SIGN>+</SIGN>
                                    <UOM>EA</UOM>
                                </QUANTITY>
                                <COLINX_AVAILDESC>No Stock</COLINX_AVAILDESC>
                                <SITELEVEL index="1">SparksNV</SITELEVEL>
                                <ORDERABLE>Y</ORDERABLE>
                                <PRIORITY>Primary</PRIORITY>
                                <COLINX_SORTORDER>1</COLINX_SORTORDER>
                                <DEFAULTIND>Y</DEFAULTIND>
                            </WHSEDETAIL>
                            <WHSEDETAIL>
                                <QUANTITY qualifier="AVAILABLE">
                                    <VALUE>1084</VALUE>
                                    <NUMOFDEC>0</NUMOFDEC>
                                    <SIGN>+</SIGN>
                                    <UOM>EA</UOM>
                                </QUANTITY>
                                <COLINX_AVAILDESC>Stock</COLINX_AVAILDESC>
                                <SITELEVEL index="1">CvilleTN</SITELEVEL>
                                <ORDERABLE>Y</ORDERABLE>
                                <PRIORITY>Secondary</PRIORITY>
                                <COLINX_SORTORDER>2</COLINX_SORTORDER>
                                <DEFAULTIND>N</DEFAULTIND>
                            </WHSEDETAIL>
                            <WHSEDETAIL>
                                <QUANTITY qualifier="AVAILABLE">
                                    <VALUE>5587</VALUE>
                                    <NUMOFDEC>0</NUMOFDEC>
                                    <SIGN>+</SIGN>
                                    <UOM>EA</UOM>
                                </QUANTITY>
                                <COLINX_AVAILDESC>Next 2 weeks</COLINX_AVAILDESC>
                                <SITELEVEL index="1">CvilleTN</SITELEVEL>
                                <ORDERABLE>Y</ORDERABLE>
                                <PRODORDID>SCHD</PRODORDID>
                                <PRIORITY>Secondary</PRIORITY>
                                <COLINX_SORTORDER>3</COLINX_SORTORDER>
                                <DEFAULTIND>N</DEFAULTIND>
                            </WHSEDETAIL>
                            <WHSEDETAIL>
                                <QUANTITY qualifier="AVAILABLE">
                                    <VALUE>2474</VALUE>
                                    <NUMOFDEC>0</NUMOFDEC>
                                    <SIGN>+</SIGN>
                                    <UOM>EA</UOM>
                                </QUANTITY>
                                <COLINX_AVAILDESC>Beyond 2 weeks</COLINX_AVAILDESC>
                                <SITELEVEL index="1">CvilleTN</SITELEVEL>
                                <ORDERABLE>Y</ORDERABLE>
                                <PRODORDID>SCHD</PRODORDID>
                                <PRIORITY>Secondary</PRIORITY>
                                <COLINX_SORTORDER>4</COLINX_SORTORDER>
                                <DEFAULTIND>N</DEFAULTIND>
                            </WHSEDETAIL>
                        </COLINX_PRODAVAIL>
                        <COLINX_PRODAVAIL>
                            <DEFAULTIND>N</DEFAULTIND>
                            <COLINX_SORTORDER>2</COLINX_SORTORDER>
                            <PACKING>01</PACKING>
                            <QUANTITY qualifier="LOTSIZEMIN">
                                <VALUE>210</VALUE>
                                <NUMOFDEC>0</NUMOFDEC>
                                <SIGN>+</SIGN>
                                <UOM>EA</UOM>
                            </QUANTITY>
                            <QUANTITY qualifier="LOTSIZEMLT">
                                <VALUE>210</VALUE>
                                <NUMOFDEC>0</NUMOFDEC>
                                <SIGN>+</SIGN>
                                <UOM>EA</UOM>
                            </QUANTITY>
                            <WHSEDETAIL>
                                <QUANTITY qualifier="AVAILABLE">
                                    <VALUE>840</VALUE>
                                    <NUMOFDEC>0</NUMOFDEC>
                                    <SIGN>+</SIGN>
                                    <UOM>EA</UOM>
                                </QUANTITY>
                                <COLINX_AVAILDESC>Stock</COLINX_AVAILDESC>
                                <SITELEVEL index="1">CvilleTN</SITELEVEL>
                                <ORDERABLE>Y</ORDERABLE>
                                <PRIORITY>Secondary</PRIORITY>
                                <COLINX_SORTORDER>5</COLINX_SORTORDER>
                                <DEFAULTIND>N</DEFAULTIND>
                            </WHSEDETAIL>
                            <WHSEDETAIL>
                                <QUANTITY qualifier="AVAILABLE">
                                    <VALUE>840</VALUE>
                                    <NUMOFDEC>0</NUMOFDEC>
                                    <SIGN>+</SIGN>
                                    <UOM>EA</UOM>
                                </QUANTITY>
                                <COLINX_AVAILDESC>Next 2 weeks</COLINX_AVAILDESC>
                                <SITELEVEL index="1">CvilleTN</SITELEVEL>
                                <ORDERABLE>Y</ORDERABLE>
                                <PRODORDID>SCHD</PRODORDID>
                                <PRIORITY>Secondary</PRIORITY>
                                <COLINX_SORTORDER>6</COLINX_SORTORDER>
                                <DEFAULTIND>N</DEFAULTIND>
                            </WHSEDETAIL>
                            <WHSEDETAIL>
                                <QUANTITY qualifier="AVAILABLE">
                                    <VALUE>210</VALUE>
                                    <NUMOFDEC>0</NUMOFDEC>
